first_name = input("Enter your first name")
second_name = input("Enter your second name")
print(first_name, second_name, sep=" ")
print(second_name, first_name, sep=", ")
print(second_name+"\t"+first_name)
